//
// Created by Marek on 27.12.2017.
//

#ifndef PJC_SEM_WORDCOUNT_SZELEMAR_CONTROLLER_HPP
#define PJC_SEM_WORDCOUNT_SZELEMAR_CONTROLLER_HPP

using namespace std;

#endif //PJC_SEM_WORDCOUNT_SZELEMAR_CONTROLLER_HPP
